version: "3.8"
services:
  users_database:
    image: postgresql:latest
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: ${USER_DB_USER}
      POSTGRES_PASSWORD: ${USER_DB_PASSWORD}
      POSTGRES_DB: ${USER_DB}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      
  events_database:
    image: postgres:latest
    container_name: events_db
    restart: always
    environment:
      POSTGRES_USER: ${EVENTS_DB_USER}
      POSTGRES_PASSWORD: ${EVENTS_DB_PASSWORD}
      POSTGRES_DB: ${EVENTS_DB_NAME}
    ports:
      - "5434:5432"  # Exposed on a different port
    volumes:
      - events_pgdata:/var/lib/postgresql/data  
  
  backend:
    build: .
    container_name: go_backend
    environment:
      - USER_DATABASE_URL=postgres://${USER_DB_USER}:${USER_DB_PASSWORD}@user_database:5432/${USER_DB_NAME}
      - EVENTS_DATABASE_URL=postgres://${EVENTS_DB_USER}:${EVENTS_DB_PASSWORD}@events_database:5432/${EVENTS_DB_NAME}
    depends_on:
      - user_database
      - events_database
    ports:
      - "8080:8080"

  gateway:
    image: nginx:latest
    container_name: api_gateway
    volumes: 
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - backend
volumes:
  pgdata: